const sellers = [
  'Alejandra Uribe',
  'Barbara Toloza',
  'Camila Pereira',
  'Carolina Heyermann',
  'Catalina Riffo',
  'Constanza Lemus',
  'Emilia Paredes',
  'Emilia Salinas',
  'Estefi Iturrieta',
  'Florencia Prochelle',
  'Francisca Sanchez',
  'Francisca Sanz',
  'Giuliana Salcedo',
  'Joctan Clavo',
  'Josefina Reyes',
  'Marcela Cespedes',
  'Maria Quiroz',
  'Mario Arias',
  'Paulina Campos',
  'Raúl Roa',
  'Rodrigo Jimenez',
  'Sofía Acuña',
  'Sofía Moreno',
  'Sofía Villavicencio',
  'Tamara Ubilla',
  'Tomás Figueroa',
  'Vicente Reyes',
  'Victoria Cespedes',
];

export default sellers;
