const sellers = [
  'Alejandra Uribe',
  'Almendra Diaz',
  'Barbara Toloza',
  'Bruno Rosati',
  'Camilo	Rivera',
  'Constanza Lemus',
  'Diego Quezada',
  'Fernanda Goldfrab',
  'Gabriela Sepulveda',
  'Gaetan	Patenotre',
  'Ignacia Pizarro',
  'Ignacio Neira',
  'Jose Toro',
  'Loreto Piña',
  'Marcela Cespedes',
  'Mariana Gonzalez',
  'Mario Espinola',
  'Maximiliano Torres',
  'Rodrigo Avila',
  'Rodrigo Jimenez',
  'Rosario Barria',
  'Sebastian Carrasco',
  'Sofia Olmedo',
  'Sofia Moreno',
  'Stephanie Chan',
  'Tomas Vargas',
  'Vicente Garrido',
  'Vicente Aburto'
];

export default sellers;
